### ISSUE TITLE
backtick marks to jump back to immediate position I came from

### ISSUE THREAD

**Issue by alok-mishra** [t9md/atom-vim-mode-plus#384]
I want to be able to use two back ticks to able to jump to the last position I came from if I'm using G or / search.

> ``

In vim-mode-plus, this is sort of working, as it jumps to the position where maybe a last mark was set but not necessarily where you came from.  i.e. if you were at line 20 and jumped to line 40 (40G), then jumped to line 60 (60G). Now if you use (``)

Expectation: Jumps to line 40
Actual; Jumps to line 20 (sometimes)
But this isn't consistent, as for example if jumped to last line (G), somehow the last line gets stuck as the last position and no matter where you jump it keeps jumping to the last line on two backticks (``)

Using the search functionality adds additional confusion as this does not also jump back to where you came from, but maybe some other mark that was made.

In vim app, it does go to the immediate last position on both G and / search. Or please let me know if I'm not using something properly 

```
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by t9md** [comment]
Pure vim has ctrl-i and ctrl-o command to jump around your cursor-position-history.
So I created this below.

https://atom.io/packages/cursor-history

**Comment by alok-mishra** [comment]
Thank you very much for that package, I'll check that out. Would there be a way to map two backticks to toggle the cursor-history:next and previous without compromising other marks getting/setting behavior.  That might be enough to simulate the same behavior.

And possibly should there be an enhancement to set the ` and ' marks as the place you jumped from automatically.

**Comment by t9md** [comment]
> And possibly should there be an enhancement to set the ` and ' marks as the place you jumped from automatically.

Yes, I want to, but in Atom, there is many command which is not vim-mode-plus's.
And many packages move cursors internally, so tracking each cursor position with avoiding unwanted remembering is almost impossible.

I want to implement feature without messing up things, one ida to do that is enhance cursor-history to have  special integration with vim-mode-plus.

Anyway, its not easy, will postpone till I have clear view for strategy to achieve that.

**Comment by t9md** [comment]
I think this has to be perfect.
What I can do to make ``` `` ``` more useful?

# TODO
- [ ] Auto-update ``` ` ``` mark after operationStack finished with currentCursor position.
- [ ] But only when commands are considerable as **jump** command
- [ ] What's commands are **jump** command? start with `gg`, `G`, `/`, `?` first.

**Comment by alok-mishra** [comment]
This is great, thanks for putting it on the list.  It's up to you how far you want to take it.  Also single quotes (') in Vim let you jump to first character of line.

I know Vim has a lot of functionality regarding marks, but you're right, this doesn't have to be perfect and would be too excessive anyway.

According to the Vim Help on [Marks](http://vimhelp.appspot.com/motion.txt.html#mark-motions), there are many commands that make it a jump, like %, n, N, H, M, L.  I think "n" and "N" would provide more value along with ones you mentioned (gg, G, /, ?)

Thanks, if I can help, I'll try.

**Comment by plbowers** [comment]
From the vim help:

8. Jumps					*jump-motions*

A "jump" is one of the following commands: "'", "`", "G", "/", "?", "n",
"N", "%", "(", ")", "[[", "]]", "{", "}", ":s", ":tag", "L", "M", "H" and
the commands that start editing a new file.  If you make the cursor "jump"
with one of these commands, the position of the cursor before the jump is
remembered.  You can return to that position with the "''" and "``" command,
unless the line containing that position was changed or deleted.

I would second the desire to be able to use single-quote in addition to back-quote to move to these (i.e., double single-quote should take me back to the same line I was on). I use this more often than the back-quotes because it is right there on the home row keys and therefore faster...

**Comment by t9md** [comment]
@alok-mishra 
Will be included in next-release.
Implementation spec is in #476

**Comment by alok-mishra** [comment]
Nice! Thank you very much!
