### ISSUE TITLE
Conceptual, behavioral change from range-marker to persistent-selection

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#408]
In #363, I came up with the notion of **persistent-selection**.
What I vaguely have been thinking at that time is now getting clear.

So this is the time of conversion.
The amount of code change is not big, but great change for accessibility and easy-to-understand.

I don't think no user other than me use range-marker in daily-basis.
But with this change, many advanced vmp user will use this feature in their daily programming(I hope so, since it's effective).

# TODO

- [x] Rename range-maker to persistent selection
- [x] CSS style just use same color as of Atom's selection
- [x] Make this as configuration option?  `autoSetPersistentSelectionAsTarget`.
- [x] And I want it's default to `true`

# Implementation spec

- [x] persistent-selection is treated as one of selection.
- [x] when persistent-selection is mutated it immediately removed as same manner like `preset-occurrence`

# Behavioral changes

### Short

- Current: User have to specify `i r`  as target explicitly to apply operator onto `range-marker`
- AutoSet: If `persistent-selection`(new name of `range-marker`) automatically set as target if exists.

### Current
When user create `range-marker` and it exist in editor.
User can apply operator to that `range-marker`(pre-selected-target) by `i r`.
So `g U i r` apply uppercase to all text within `range-marker`.

### New behavior
When use create `persistent-selection` and it exists in editor.
User can apply operator to that `persistent-selection` without explicitly specifying target.
So only `U`, uppercase all the text in the `persistent-selection`.

# What's was change in my mind? Why I couldn't do it before?

This autoSetAsTarget feature seem to too aggressive for me at that time.
But after I added preset-occurrence-marker(not released yet), I found it's very powerful and also found it's feature is very similar, duplicating with current `range-marker`.
But yes, occurrence-marker is far more accessible.
So most of `range-marker`'s features are superseded by `preset-occurrence-marker`.

So I thinks now I can simplify it, converting **general-purpose-but-not-easy-to-use-range-marker** to more **purpose-specific-persistent-selection** feature.

**Comment by t9md** [comment]
As far as I tested behavior, it's super powerful.
User can treat it as selection, so it's intuitive , easy-to-use.
What a big flight in this pending release!

**Comment by t9md** [comment]
# Roll up

## persistent-occurrence? vs persistent-selection?

- preset-occurrence-marker: instead of using `o` in the middle of operator, user can preset what a `occurrence` is preliminarily. is used to specify **occurrence**

- persistent-selection: instead of telling operator what a target range is via visual-mode, user can specify target range preliminarily. is used to specify **target**

## Operator demands target to which operator operates on

- Most operator require target
- If operator cannot get satisfied with target, it enter `operator-pending-mode` to get target from user. In other words, `operator-pending` is `target-waiting` mode.
- Some operator is pre-targeted so it's operator but it don't have to get target from user(won't enter `operator-pending`. e.g `D` is pre-targeted with `$` motion. so `D` is short hand of `d $`.

## What a target is?

- Target is instance of `Motion` or `TextObject`
- `TextObject` defines `start` and `end` of target. 
- `Motion` is essentially used to move cursor, so is only define final-target-position.
- When `Motion` is used as **target**, its `start` is defined as current-cursor-position, in this way motion motion can have ranges.

## Target can be re-selected
- When occurrence exists, occurrences intersecting with target-range is re-selected as target.

## Operator just apply operation on target

- Operator just works on target(don't care if it is occurrence-reselected-target or normal-target)
