### ISSUE TITLE
old TODO as record around vim-mode fork and vim-mode-plus release

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#429]
Following TODO was on wiki, but I don't want to keep this as wiki page.
So as record I put this not here for future reference.

----------------
Here is the old TODO which I used to manage tasks from at initial fork(2015.8.1) to around 2015.11.
I preserve here since it gives some information what/how I changed upstream vim-mode.

See [TODO Priority](https://github.com/t9md/atom-vim-mode-plus/issues/25).

- [ ] Dont't do moveRight and moveLeft to adjust selection in `Motion::selectInclusive()` it complicate other motion. and prevent to stop at EOL in `l`, `$`
- [x] Don't use typeCheck function like `isOperator()`, `isYank()` any more. instead use `instantOf` for being explicit what it meant to.
- [x] Don't depend on `atom.commands.onDidDispatch`, instead simply ensure cursor not put endOfLine **only for vim-mode-plus's command**.
- [ ] Write spec for lots of UI effect. hover, search counter etc.
- [ ] Write tutorial for new Operator, TextObjet.
- [x] Allow quoted-Pair to select quoted string outside of cursor postion within line(I don't like this behavior)?
- [x] Make AnyPair TextObject expandable.
- [x] When hover Icon disabled, icon position is not at original cursor position.
- [x] Make independent showHoverCounter from showHover config parameter.
- [x] Use single scope for custom selection property.
- [x] Change subscription link to use vimState as hub.
- [x] Improve Visual mode: complete cursor visualization and switch between submode.
  - [x] Shift between submode properly restoring column and reversed state.
  - [x] show cursor: characterwise
  - [x] show cursor: linewise(decided to not try to show cursor)
  - [x] show cursor: blockwise
- [x] Improve search and introduce incrementalSearch.
- [x] Cancellation of operation on event subscription.
- [x] Improve visual-block's line end selection and sync range between selections.
- [ ] Spec re-write 2nd round to compact and simple description for each spec.
- [x] Select fold without expanding
- [x] Show cursor in visual-mode(now characterwise only) without hacking `Cursor.prototype`.
- [x] Support visual-block by incorporating with [vim-mode-visual-block](https://github.com/t9md/atom-vim-mode-visual-block).
- [x] Support web-font(?) font-awesome etc. to show on overlay hover.
- [x] `0` is accessible position than `^` so provide config option to behave `0` like `^`(I want single `0` behave as `^`). Removed this feature after evaluation, I don' need this.
- [x] Show emoji that representing current operation.
- [x] Get user's input with consistent manner via `@vimState.input`.
- [x] Flash(highlight) region for yanked, pasted, indented for giving instant feedback to user, beneficial especially used as operator like `yip`, `=ip`.
- [x] Don't change cursor position after yank, indent, toggle(break compatibility to Vim, but I thinks this is bettter).
- [x] New Operator for Surround, DeleteSurround, ChangeSurround.
- [x] Show current Register, Mark, Count as overlay decoration to giving instant feedback to user.
- [x] New Operator for ToggleLineComments, Camelize, Dasherize, Underscore.
- [x] New TextObject for Comment, Indent.
- [x] Rewrite spec to be able to write test intuitively.
- [x] Support new TextObject for Indent, and Comment.
- [x] Support new Operator ReplaceWithRegister.
- [x] Make opStack independent
- [x] Eliminate Prefix.Repeat object. Count is provided as global to object by inheriting Base.
- [x] TOM can respond to its class(e.g. isTextObject()?)
- [x] Realtime observation of OperatonStack.
- [x] Eliminate `vimState.linewiseAliasedOperator()` [done](https://github.com/t9md/vim-mode/commit/9fc615e968ad08a5633490c71defeb4008cabc65)
- [x] Readability improve for `registerOperationCommands`. Partially, experimentally done.
- [x] Operation really need to be List(`[]`) of Operation? Explicitly define operation is more neat and descriptive. done, :fire: operator with list form.
- [x] Consolidate files, remove subdirectories, all files are located directly under lib.(for easiness of refactoring, faster startup time.)
- [x] Consolidate arguments passed to each TOM. vimState should be available to all TOM. editor and editorElement should be removed since its available via vimState. This consistency will reduce developer's confusion while working on multiple TOMs.
- [x] Remove MotionWithInput, it'd be OK by providing getInput() methods on Base class. it will remove some complexity. [done](https://github.com/t9md/vim-mode/commit/0c7a4185ff4974ffe316459d8a98d2764057198d).
- [x] Remove OperatorWithInput, it'd be OK by providing getInput() methods on Base class. it will remove some complexity.
- [x] Eliminate Prefix.Register. make it available via vimState.
- [x] By eliminating Prefix.Register and Prefix.Repeat, remove Prefix class itself. [done](https://github.com/t9md/vim-mode/commit/5ac09c41beea779dd157ae76230d4c76b99989d4)
- [x] `introduce ViewModel.onDidGetInput(callback)` for operation which need user input.
- [x] Eliminate Input class, its just proxying user-input. [done](https://github.com/t9md/vim-mode/commit/b18f7f74f549e76e103335790f9af2cbf2599ac4)
- [x] Slim vim-state.coffee
  - [x] Auto mapping from command-name to corresponding class.
  - [x] Separate mode handling to ModeManager
- [x] improve introspection report to describe keymap to corresponding class(by consulting `atom.keymap`).
- [x] Recheck unnecessary count passing function.
