### ISSUE TITLE
Improve flashing UI effect by keyframe animation

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#496]
I noticed atom v1.13-beta use this approach.
It seems v1.12 chrome not yet support keyframe animation(from behavioral observation)

## TODO:

- [x] Improve: Style for flashing effect by borrowing atom-core's flash keyframe animation
- [x] Remove independent xxxDuration setting, since duration is controlled by `animation-duration:` css property.
- [x] Need differentiate flashing style by purpose since it demand different duration(flashOnOperate vs flashOnSearch etc).
